### ISSUE TITLE
`make clean` removes version-controlled files

### ISSUE THREAD

**Issue by JasonGross** [mit-plv/rupicola#20]
It seems a bit strange that `_CoqProject` is both version controlled and removed by `make clean`, and moreover that the contents of the file does not depend on any makefile variables.  Why not just leave it as version-controlled and get rid of the make rules?

**Comment by cpitclaudel** [comment]
>  Why not just leave it as version-controlled and get rid of the make rules?

Seems reasonable.

**Comment by JasonGross** [comment]
We no longer track `_CoqProject` in version control
